# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0003_yo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yo',
        ),
    ]
