# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0005_yo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
