# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gf', '0006_yona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yo',
        ),
        migrations.DeleteModel(
            name='Yona',
        ),
    ]
